#!/usr/bin/env node
/**
 * Move story prose out of the module the home page ships.
 *
 * The atlas workspace is a client component and imports the whole dataset,
 * so every story travels to every visitor even though only the selected
 * entry shows one. Stories are about a quarter of the dataset by size, and
 * the share grows with every writing round.
 *
 * This rewrites src/data/words.ts without the story field and writes the
 * prose to src/data/stories.ts, which the entry pages import on the server
 * and the workspace fetches on first selection.
 *
 * Idempotent: running it on an already split dataset changes nothing.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const wordsPath = join(root, "src", "data", "words.ts");
const storiesPath = join(root, "src", "data", "stories.ts");

const source = readFileSync(wordsPath, "utf8");

/**
 * Stories already moved out stay put. A later writing round appends entries
 * to words.ts with their prose inline, and this run has to fold those in
 * rather than replace the file with only the new ones.
 */
function existingStories() {
  let text = "";
  try {
    text = readFileSync(storiesPath, "utf8");
  } catch {
    return new Map();
  }
  const kept = new Map();
  const row = /^ {2}("(?:[^"\\]|\\.)*"): ("(?:[^"\\]|\\.)*"),$/gm;
  let found;
  while ((found = row.exec(text)) !== null) {
    kept.set(JSON.parse(found[1]), found[2]);
  }
  return kept;
}

// Anchor on indentation, not on field order. A place object carries its own
// slug two levels in, so a loose pattern pairs each place slug with the next
// entry's story and silently shifts the whole file by one.
const ENTRY_SLUG = /^ {4}slug: "([^"]+)",$/;
const STORY_START = /^ {4}story:(.*)$/;

const stories = existingStories();
const before = stories.size;
let slug = null;
const lines = source.split("\n");
for (let i = 0; i < lines.length; i += 1) {
  const slugMatch = ENTRY_SLUG.exec(lines[i]);
  if (slugMatch) {
    slug = slugMatch[1];
    continue;
  }
  const storyMatch = STORY_START.exec(lines[i]);
  if (!storyMatch || !slug) continue;
  // The value sits on the same line or wraps onto the next.
  const inline = storyMatch[1].trim();
  const raw = inline === "" ? lines[i + 1].trim() : inline;
  stories.set(slug, raw.replace(/,$/, ""));
}

if (stories.size === 0) {
  console.log("split-stories: no stories found, nothing to do");
  process.exit(0);
}

const stripped = source.replace(/\n {4}story:(?: "(?:[^"\\]|\\.)*",|\n {6}"(?:[^"\\]|\\.)*",)/g, "");

const body = [...stories]
  .map(([key, story]) => `  ${JSON.stringify(key)}: ${story},`)
  .join("\n");

writeFileSync(
  storiesPath,
  `/**
 * Entry prose, kept apart from src/data/words.ts so the atlas workspace does
 * not ship every story to every visitor. Entry pages import this directly on
 * the server; the workspace loads it on first selection.
 *
 * Generated by scripts/split-stories.mjs. Edit the story of a new entry here.
 */
export const STORIES: Record<string, string> = {
${body}
};

export function storyFor(slug: string): string {
  return STORIES[slug] ?? "";
}
`,
  "utf8",
);

writeFileSync(wordsPath, stripped, "utf8");
console.log(
  `split-stories: ${stories.size - before} moved, ${stories.size} total in src/data/stories.ts`,
);
